apiVersion: v1
kind: Service
metadata:
  name: {{ include "statsd.fullname" . }}
  labels:
    {{- include "statsd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: statsd
      protocol: UDP
      name: statsd
  selector:
    {{- include "statsd.selectorLabels" . | nindent 4 }}
